### PR TITLE
feat(tabs): ECL4 tabs - FRONT-4167

### PR DESCRIPTION
**Pull request by emeryro**

### CODE REVIEW

**Comment by planctus** [comment]
I wonder if we could try to tackle the accessibility issues that we still have if we re-introduce the accessibility test.
It's not straightforward, though, and it might not lead to a cleaner markup, don't know, but we could try..

**Comment by planctus** [comment]
I see this is coming from a specific rule set for this component, so i guess it's by design, but do we really need this huge padding, i wonder? 
image

**Comment by emeryro** [comment]
I checked the accessibility issue again, and indeed that would not be easy at all to fix. 
It would most probably implies changes of the markup, css and js, even possibly of the behaviour.
I'd rather keep that in a dedicated task, as it is not linked diretly to the design update.

And for the spacing, that's quite huge I agree. But that's what they requested...

**Review by planctus — APPROVED** [review]

**Comment by planctus** [comment]
I've just noticed a small issue with the RTL css: 
image

**Pull request merged**
