### PR TITLE
feat(reset): remove margin on body - INNO-837

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Add margin:0 to body
Update screenshots

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit cf0d76725159ffd2d8cdf38c9ebe6d16c2311926

https://deploy-preview-492--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit 0c26c323a4c288fab4c88d2bf700ebe03b08755b

https://deploy-preview-492--europa-component-library.netlify.com

**Review by kalinchernev — APPROVED** [review]
If CI goes green - good.
If not, we merge anyway

**Comment by drupol** [comment]
👎

**Comment by kalinchernev** [comment]
Mr. @drupol why thumbs down?

**Comment by drupol** [comment]
_If not, we merge anyway_ 👎

**Pull request merged**
