### PR TITLE
refactor(sass): improve all components (S01E07) - INNO-1020

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

language-list, link, link-block, list-item, listing, logo

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 41afb9c586ddc9ce3607c75d669018f0ded32a68

https://deploy-preview-654--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 8b56aadc6b83d16b0b7f9af39f1e8c4f43dffa94

https://deploy-preview-654--europa-component-library.netlify.com

**Review by degliwe — COMMENTED** [review]
language list overlay:
- "x" in the close isn't properly positioned (not centered vertically)

**Comment by yhuard** [comment]
@degliwe @emeryro the "x" can be centered with

```css
  display: flex;
  justify-content: center;
  align-items: center;
```

**Comment by emeryro** [comment]
display of "x" has been updated

**Review by degliwe — APPROVED** [review]

**Pull request merged**
