### PR TITLE
feat(footers): add EU version of footer - INNO-927

### PR DESCRIPTION
**Pull request by kalinchernev**
# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit fa910e85fed941f8d2e6a6606ec43fbc9be2c8db

https://deploy-preview-606--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 2d985df65d235bf77ae15277e2aa67689e8b1ffc

https://deploy-preview-606--europa-component-library.netlify.com

**Comment by kalinchernev** [comment]
Short summary of changes since fa910e8
- remove fractal-specific config tests from generic
- based on comment from @CFilipa in jira ticket
-- extra spacing in eu footer columns
-- added link for other social media, which was hopefully right thing to make uniform, rather than making additional specific changes for last link in social links in footer, open for comments on this
- removed eu-specific deps from generic footer, updates in versions of deps correspondingly
- updated contexts, twig templates and full preview in all sub-systems, in order to receive ecl grid classes similarly to what was achieved to the previous point before fa910e8
- added eu-specific styling in all links in eu footer to be like standalone, from css, rather than context for twig, since some cases, like external links, need `external` as variant and it seems more easier to implement for consumers of the component

**Comment by yhuard** [comment]
Replaced by https://github.com/ec-europa/europa-component-library/pull/607

**Pull request closed without merging**
