### PR TITLE
fix(ecl-editor): fix css conflict - FRONT-1697

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Fix css specificity conflict with file component

### CODE REVIEW

**Review by kalinchernev — CHANGES_REQUESTED** [review]
I tested the fix on the page given in the ticket description.
The hover state will also need the update

video

**Comment by emeryro** [comment]
@kalinchernev the hover/focus state should be covered already: https://github.com/ec-europa/europa-component-library/blob/FRONT-1697-editor-conflict/src/systems/ec/implementations/vanilla/packages/ec-editor/_ec-editor--button.scss#L31

**Comment by kalinchernev** [comment]
I think some tweaks are still necessary. The

```css
background-color: $ecl-color-blue-130;
``` 

make so that when hovering over the button it becomes unreadable.

**Comment by emeryro** [comment]
yes, but my point is: in the compiled css it will be handled already with the proposed modification.
here is the scss:
```
.ecl-editor button:not(.ecl-file__translation-toggle),
.ecl-editor input[type='button'],
.ecl-editor input[type='submit'] {
  appearance: none;
  background: none;
  background-color: $ecl-color-blue-100;
  [...]

  &:hover,
  &:focus,
  &:active {
    background-color: $ecl-color-blue-130;
    text-decoration: none;
  }
```
So unless I'm wrong, this specific button won't have the blue background at all (including on hover)

**Review by kalinchernev — APPROVED** [review]

**Pull request merged**
