### PR TITLE
refactor(browserslist): change browsers coverage - INNO-1434

### PR DESCRIPTION
**Pull request by yhuard**

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 2e00f446e4c34913a218dd4b1a9ae174820892df

https://deploy-preview-1069--europa-component-library.netlify.com

**Comment by yhuard** [comment]
Hacking node_modules/autoprefixer/lib/browsers.js to get the browsers list as parsed by browserslist... basically I rewrote `Browsers.prototype.parse`: 

```js
  Browsers.prototype.parse = function parse(requirements) {
    const browsers = browserslist(requirements, {
      stats: this.stats,
      path: this.options.from,
      env: this.options.env,
    });

    console.log(browsers);

    return browsers;
  };
```

If the main `browserslist` config file contains `> 0.2%`, then the list of browsers is:

```
[ 'and_chr 64',
  'and_ff 57',
  'and_uc 11.8',
  'android 4.4.3-4.4.4',
  'android 4.4',
  'android 4.2-4.3',
  'chrome 65',
  'chrome 64',
  'chrome 63',
  'chrome 62',
  'chrome 55',
  'chrome 49',
  'chrome 29',
  'edge 16',
  'firefox 59',
  'firefox 58',
  'firefox 52',
  'ie 11',
  'ios_saf 11.0-11.2',
  'ios_saf 10.3',
  'ios_saf 10.0-10.2',
  'ios_saf 9.3',
  'op_mini all',
  'opera 51',
  'safari 11',
  'safari 10.1',
  'samsung 6.2',
  'samsung 5',
  'samsung 4' ]
```

no trace of iOS Safari 8... (which is what we try to target here)

**Comment by yhuard** [comment]
with `> 0.1%`:

```
[ 'and_chr 64',
  'and_ff 57',
  'and_uc 11.8',
  'android 4.4.3-4.4.4',
  'android 4.4',
  'android 4.2-4.3',
  'chrome 65',
  'chrome 64',
  'chrome 63',
  'chrome 62',
  'chrome 61',
  'chrome 60',
  'chrome 59',
  'chrome 58',
  'chrome 56',
  'chrome 55',
  'chrome 49',
  'chrome 48',
  'chrome 29',
  'edge 16',
  'edge 15',
  'firefox 59',
  'firefox 58',
  'firefox 57',
  'firefox 56',
  'firefox 52',
  'firefox 48',
  'ie 11',
  'ie 10',
  'ie 9',
  'ie 8',
  'ie_mob 11',
  'ios_saf 11.0-11.2',
  'ios_saf 10.3',
  'ios_saf 10.0-10.2',
  'ios_saf 9.3',
  'op_mini all',
  'opera 51',
  'safari 11',
  'safari 10.1',
  'safari 9.1',
  'samsung 6.2',
  'samsung 5',
  'samsung 4' ]
```

note that the `caniuse-lite` db has not been updated for a while

**Comment by yhuard** [comment]
now, if i run `yarn upgrade` and then re-run the compiling script with `> 0.2%`, I get: 

```
[ 'and_chr 71',
  'and_uc 11.8',
  'android 4.4.3-4.4.4',
  'chrome 72',
  'chrome 71',
  'chrome 70',
  'chrome 69',
  'chrome 67',
  'chrome 63',
  'chrome 61',
  'chrome 49',
  'edge 18',
  'edge 17',
  'firefox 65',
  'firefox 64',
  'firefox 52',
  'ie 11',
  'ios_saf 12.0-12.1',
  'ios_saf 11.3-11.4',
  'ios_saf 11.0-11.2',
  'ios_saf 10.3',
  'ios_saf 9.3',
  'ios_saf 8',
  'op_mini all',
  'opera 58',
  'opera 57',
  'safari 12',
  'safari 11.1',
  'samsung 8.2',
  'samsung 7.2-7.4',
  'samsung 4' ]
```

`ios_saf 8` is now here ;)

**Comment by yhuard** [comment]
Before:

image

After:

image

Now there's an issue on the fractal theme, we should remove `.Pen-tabs { height: 100% }`

**Comment by yhuard** [comment]
Counterintuitively the latest compiled CSS (using `> 0.2%` with the updated dependencies) is smaller than the old one: `22098 bytes` vs `22219 bytes` (gzipped) 🤔

**Comment by yhuard** [comment]
Now I'm trying to update more dependencies...

**Comment by yhuard** [comment]
now, with the latest updates + CSS fix:

image

**Comment by yhuard** [comment]
`yarn browserslist -v`

> browserslist 3.2.8

`yarn browserslist`

> and_chr 71
> and_uc 11.8
> android 4.4.3-4.4.4
> chrome 72
> chrome 71
> chrome 70
> chrome 69
> chrome 67
> chrome 63
> chrome 61
> chrome 49
> edge 18
> edge 17
> firefox 65
> firefox 64
> firefox 52
> ie 11
> ios_saf 12.0-12.1
> ios_saf 11.3-11.4
> ios_saf 11.0-11.2
> ios_saf 10.3
> ios_saf 9.3
> ios_saf 8
> op_mini all
> opera 58
> opera 57
> safari 12
> safari 11.1
> samsung 8.2
> samsung 7.2-7.4
> samsung 4

**Comment by yhuard** [comment]
Lessons learned: 
- always check the supported browsers
- attach the list of supported browsers and browserslist's version number to the release ⚠️ 

Now the question is what config should we use?

**Comment by yhuard** [comment]
Maybe we should also display the version of `caniuse-lite`...

ECL Builder should output the browser coverage at least.

**Review by degliwe — APPROVED** [review]

**Pull request merged**
