### PR TITLE
feat(grid): implement new grid - INNO-1132

### PR DESCRIPTION
**Pull request by yhuard**
Basically, the same 12-columns grid we had but with the new breakpoints and container widths.

Also, `.ecl-col, .ecl-col-sm, ...` without the number of columns is not possible anymore.

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 16b478c019c87ba7b21a16d28eed12d149f2e125

https://deploy-preview-768--europa-component-library.netlify.com

**Review by degliwe — DISMISSED** [review]

**Review by degliwe — DISMISSED** [review]

**Review by degliwe — DISMISSED** [review]
please adjust props format to support the component  "DisplayTokens"

**Comment by yhuard** [comment]
breakpoints/grid props are now displayed in the docs (both EC and EU)

**Review by degliwe — APPROVED** [review]
Looks great

**Pull request merged**
