### PR TITLE
fix(gallery): prevent body scroll - INNO-1428

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Prevent page body from scrolling when gallery overlay is displayed

To test: 
- reduce window width to have a vertical scrolling on the gallery
- click on a gallery item to open the overlay
- no scrollbar displayed, scrolling with the mouse does not affect the display
- close the overlay; body hasn't scrolled (last selected gallery item is focused)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 84a100d8ab47dffe695158689fd2d5ec62bcac86

https://deploy-preview-1063--europa-component-library.netlify.com

**Review by yhuard — CHANGES_REQUESTED** [review]
- why `document.body.scroll`?
- can we prevent the scroll jump? (adding/removing the disablescroll class at the right time)

**Comment by emeryro** [comment]
- `document.body.scroll` isn't mandatory.. I can remove it
- what scroll jump? I don't have any...

**Review by yhuard — CHANGES_REQUESTED** [review]
one more thing: if the modal is longer than the viewport height, we can't scroll in it 

maybe a `overflow: auto;` on `.ecl-gallery__overlay[open]` could solve it

**Review by yhuard — APPROVED** [review]

**Pull request merged**
