### PR TITLE
fix(multi-select): check if data-ecl-select-all attribute is set - FRONT-1274

### PR DESCRIPTION
**Pull request by papegaill**
# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)
- [ ] The redirects in `src/website/src/routes/Redirects.jsx` are up-to-date

### CODE REVIEW

**Comment by emeryro** [comment]
I'm a little confused here: the ticket was about fixing some potential js error, in the (unplanned) case where no label is provided for select all.
This is done in this PR, the js file.

But what about the css? I don't think that's necessary to add complexity to the markup (with an additional class), for a case that should never occurs.

So I'd keep only the extra test in js (for both EC and EU), and do not change the markup/css.

**Comment by papegaill** [comment]
@emeryro I added this specific class only for the "select all" option because if that option is not displayed, then the first option will be styled with a bottom border, which is strange:

Screenshot 2020-07-17 at 15 01 18

I don't think it's that complex but if you want I can remove the selector and css part for it.

**Comment by emeryro** [comment]
@papegaill ok, but then we should use a css class related to the select component, not the checkbox.
Here you added `ecl-checkbox--all`, which seems to be a variant of checkboxes (according to the name). It should be something like `ecl-select__multiple-all` instead

Also, please add the modification to EU system too

**Comment by papegaill** [comment]
@emeryro thank you for your suggestion, I just updated the PR accordingly.

**Review by emeryro — APPROVED** [review]

**Pull request merged**
