### PR TITLE
fix(twig): normalize twig templates, pt2 - INNO-1019

### PR DESCRIPTION
**Pull request by yhuard**
Updated:
- component-form-fieldset
- component-form-file-upload
- component-form-form
- component-form-group
- component-form-help-block

Normalized: `{# Print the result #}`

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit a62b06bf8d2d99da283abeba4188a40d4bd3015e

https://deploy-preview-647--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit c6d379f5cad4ab0e533254f74596ec6eba79f313

https://deploy-preview-647--europa-component-library.netlify.com

**Review by emeryro — COMMENTED** [review]
Is there a reason why you didn't use generic component template in most system components here?

**Comment by yhuard** [comment]
@emeryro twig.js + blocks = 💔

**Review by emeryro — APPROVED** [review]

**Pull request merged**
