### PR TITLE
feat(design-tokens): rely on design tokens only - INNO-1209

### PR DESCRIPTION
**Pull request by yhuard**
No more colors or spacing declarations in SCSS files, everything is derived from the design tokens.

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 17fd5029b8ea55c2ad02188cc43c76943110bf5c

https://deploy-preview-795--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit a333610649e2be4cf9eea2d0bf44407d801cec9d

https://deploy-preview-795--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit c168fa5d426128f07aa1ce6486a38da6df27362c

https://deploy-preview-795--europa-component-library.netlify.com

**Review by emeryro — APPROVED** [review]
It seems to be good.
I didn't check display of old components (most probably broken), but new ones are fine.

**Pull request merged**
