### PR TITLE
fix(label): use inline display - INNO-1704

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Update label display to not use display block

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 174edd1e8dde8d6c0ea30393ee79e4afdf990515

https://deploy-preview-1235--europa-component-library.netlify.com

**Review by yhuard — CHANGES_REQUESTED** [review]
one more thing: `.ecl-radio__group--binary .ecl-radio` should have `display: inline-flex;` instead of `display: inline-block;` (there's a 4px difference 😱)

**Review by yhuard — CHANGES_REQUESTED** [review]
Binary radio groug is now broken :'(

**Review by yhuard — APPROVED** [review]
I can't find any issues :'(

**Pull request merged**
