### PR TITLE
refactor(page-header): use composition for metas - INNO-668

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

No more "cheap" integration of components

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [x] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [x] I have checked the dependencies
- [x] I have given the fractal status “ready” to my component
- [x] I have declared `@define mycomponent` in the SCSS file
- [x] I have specified `margin: 0;` on the CSS component
- [x] I have provided tests
- [x] I follow the naming guidelines
- [x] the component supports composition
- [x] there are no hardcoded strings (all content come from the context)
- [x] I have filled the README.md file (at least a few lines)
- [x] My component is listed in the root README
- [x] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit de16edc19a8dc23981cb28ce8408a4a640684336

https://deploy-preview-466--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit f01b4996f521354f0894ec3b4428a8374ab70900

https://deploy-preview-466--europa-component-library.netlify.com

**Review by degliwe — CHANGES_REQUESTED** [review]
The context of the templates using "page header" component needs to be updated

**Comment by emeryro** [comment]
Pages template context has been fixed

**Review by degliwe — APPROVED** [review]

**Pull request merged**
