### PR TITLE
feat(footer-standardized): add component - INNO-1770

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

specs: https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Standardised+Footer+-+Design+Specifications

Note: component is not displayed on the website yet, as the new structure isn't available. Playground link: https://deploy-preview-1313--europa-component-library.netlify.com/playground/ec/?path=/story/components-footers-standardised--default

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 319ac61b56f727982894d7c624aa00eeeabd0ba1

https://deploy-preview-1313--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit bee3a15e1414e93398cd268406e76b607452daa0

https://deploy-preview-1313--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit af983d10e63c36cda24c909b3d40061fd53d7d49

https://deploy-preview-1313--europa-component-library.netlify.com

**Review by yhuard — APPROVED** [review]
LGTM

**Pull request merged**
