### PR TITLE
feat(accordion): add component - INNO-1232

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Add accordion according to [the specifications](https://webgate.ec.europa.eu/CITnet/confluence/pages/viewpage.action?spaceKey=NEXTEUROPA&title=Accordion+Design+Specifications)

Note that modifications to the button is already part of another PR, not merged yet (galleries)

Resources for markup and accessibility:
- https://davatron5000.github.io/a11y-nutrition-cards/components/accordion
- https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html
- https://inclusive-components.design/collapsible-sections/

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 0b7d00540cb861210c10709e3d465028f283c845

https://deploy-preview-992--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 191693eb32c1f9adb0c7196b923b777346fb836c

https://deploy-preview-992--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 800937fb3adf5b62d233b93415e76b6e475c2574

https://deploy-preview-992--europa-component-library.netlify.com

**Review by yhuard — CHANGES_REQUESTED** [review]
in a nutshell:
- please use a definition list instead of divs
- please use a "xs" vertical padding on the button (instead of around the icon)
- wait for feedback on the line-height for the button
:)

**Comment by emeryro** [comment]
Markup has been improved, and padding fixed.
For the line height, if we don't recieve an answer quickly, we can still change it afterward as it is only css. So we could already merge it.

**Review by yhuard — APPROVED** [review]
Technically + semantically ok

**Pull request merged**
