### PR TITLE
feat(content): update usage blockquote - no issue

### PR DESCRIPTION
**Pull request by Yaomimi**
# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 2ee2efe61505f1df6ebfad4d67bbc5cb15bf570f

https://deploy-preview-770--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 7846ab481230de1abbd510bf38e8319fb051f176

https://deploy-preview-770--europa-component-library.netlify.com

**Comment by yhuard** [comment]
Hi @Yaomimi 

Is this PR ready for a review or are you still working on it?

Thanks!

**Comment by Yaomimi** [comment]
Hi @yhuard It is ready for review. Thanks.

**Comment by yhuard** [comment]
Merged. Thank you for this PR!

**Comment by Yaomimi** [comment]
@yhuard Thanks a lot. Basically when I produce the content (duplicate from ec to eu), they have to be treated as two PRs, right?

**Pull request merged**
