### PR TITLE
feat(lang-select-sites): refactoring the component - INNO-529

### PR DESCRIPTION
**Pull request by kalinchernev**
Pull is actually solving INNO-529, which is a site header, not a page header, but INNO-512 shows a site header in the name of a page header.

### CODE REVIEW

**Comment by yhuard** [comment]
Does not seem aligned vertically?

**Comment by kalinchernev** [comment]
Vertical alignment changed.
The tests seem to pass now, but still the build fails of a timeout...

**Comment by yhuard** [comment]
Giving it a second look :)

**Comment by yhuard** [comment]
I've merged it since the only failing test was due to a timeout (too many tests running at the same time on Sauce Labs)

**Pull request merged**
