### PR TITLE
feat(listings): add default listing - INNO-805

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Add default listings.
Refactor meta

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [x] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [x] I have checked the dependencies
- [x] I have given the fractal status “ready” to my component
- [x] I have declared `@define mycomponent` in the SCSS file
- [x] I have specified `margin: 0;` on the CSS component
- [x] I have provided tests
- [x] I follow the naming guidelines
- [x] the component supports composition
- [x] there are no hardcoded strings (all content come from the context)
- [x] I have filled the README.md file (at least a few lines)
- [x] My component is listed in the root README
- [x] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit 7e986892db30b2ce7b1eba26d1b12a206b3f4c30

https://deploy-preview-447--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit 44d53ed51b1549835743754e2ed6dcc7919f599d

https://deploy-preview-447--europa-component-library.netlify.com

**Review by degliwe — CHANGES_REQUESTED** [review]
- Meta problem visible on "Featured items"

**Comment by emeryro** [comment]
Featured items fixed

**Review by degliwe — APPROVED** [review]

**Pull request merged**
