### PR TITLE
feat(gallery): Overlay iteration - FRONT-3918

### PR DESCRIPTION
**Pull request by planctus**

### CODE REVIEW

**Review by emeryro — COMMENTED** [review]
Not sure if this is related to this update, but there are some strange display and behavior on my Firefox

blur issue:
image

close issue:
gallery

**Comment by planctus** [comment]
the blur, although i find it's an ugly thing, is there because requested by the designers, for the close button the issue is..? that the outline it's not fully visible..?
image
This is how it looks on firefox for linux..

**Comment by emeryro** [comment]
For the close, each time you close the overlay (on FF), the gallery grid is modified (the previously selected image takes full width).

**Comment by planctus** [comment]
Oh, true..it was in the picture pr where i guess this was introduced, fixed.

**Review by emeryro — APPROVED** [review]

**Pull request merged**
