### PR TITLE
docs(file): update file download's documentation - INNO-1632

### PR DESCRIPTION
**Pull request by yhuard**
https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/File+Download+-+ECL+Page+-+final

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit e4fa2b7f9c870dd37b6dfaafda1314c8423df9b1

https://deploy-preview-1204--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 4effc2627c13631237896838d648620bf1d98529

https://deploy-preview-1204--europa-component-library.netlify.com

**Review by planctus — COMMENTED** [review]
Just a question, @yhuard , i see in the wiki page the two "anatomies", desktop and mobile as two different images. Did we agree with them about only showing the desktop one in the usage page?

**Comment by yhuard** [comment]
@planctus I've reported this issue several times to the designers... We don't have an easy way to display/switch the images. They don't have an solution for this yet unfortunately :(

**Review by planctus — APPROVED** [review]

**Pull request merged**
