### PR TITLE
feat(file-upload): add basic file upload - INNO-1717

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Add default file upload (no js)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit fa625218b7aec65aae5b798fa195a565e64620d9

https://deploy-preview-1247--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 830693991d57dd1e1e7ba60d0339ca456d04a973

https://deploy-preview-1247--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit b661adfbd3f5f99e1b6eba458c773fe604cc5454

https://deploy-preview-1247--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit cb22e7e3e7f6f5c93dd7b22c45a97a66f5802d66

https://deploy-preview-1247--europa-component-library.netlify.com

**Review by yhuard — APPROVED** [review]
LGTM

**Pull request merged**
