### PR TITLE
feat(file-upload): upload multiple files - INNO-2065

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Update file upload component to allow multiple file upload, with file name displayed

### CODE REVIEW

**Comment by emeryro** [comment]
File upload has been approved by designers (https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/07.+File+upload?focusedCommentId=907428791#comment-907428791)
We can move forward here

**Review by papegaill — DISMISSED** [review]
@emeryro Tested on IE11 and Edge, all good and Specs are ok too. I updated the PR in order to have (file-size - type) bellow filenames in the upload list. Can you have a look on this?

**Comment by emeryro** [comment]
@papegaill file size and type are working well. I just updated the css class name to be consistent with other components, and reduced number of decimal to 1 as on the mockups.
If that's fine, please approve and merge the PR

**Review by papegaill — APPROVED** [review]
@emeryro Thank you for updates.

**Pull request merged**
