### PR TITLE
feat(social-media-links): fix display of last link - INNO-838

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Put "other social media" link on a new line

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [x] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [x] I have checked the dependencies
- [x] I have given the fractal status “ready” to my component
- [x] I have declared `@define mycomponent` in the SCSS file
- [x] I have specified `margin: 0;` on the CSS component
- [x] I have provided tests
- [x] I follow the naming guidelines
- [x] the component supports composition
- [x] there are no hardcoded strings (all content come from the context)
- [x] I have filled the README.md file (at least a few lines)
- [x] My component is listed in the root README
- [x] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit feb545e8ba928aab8451b5e88354244617436a11

https://deploy-preview-489--europa-component-library.netlify.com

**Comment by drupol** [comment]
@emeryro Do you think it would be possible to do this for the last element in a list ?

In drupal we are using the theme 'item_list' to render those links and it would be much easier if we could handle this singularity just using CSS.

Let me know.

**Comment by emeryro** [comment]
Yes, it is possible, but are we sure that the last link will always be this one? (ie, is it possible that there is no "other social media" link?)

**Comment by drupol** [comment]
That's a discussion to have with Filipa and/or Kevin indeed :-)

**Comment by emeryro** [comment]
For now I'll do it by styling the last link, as it easier for you, it will be updated if needed.

**Comment by drupol** [comment]
Yes please, we'll see if it's ok for Kevin and Filipa.

**Comment by kalinchernev** [comment]
Good to have input by Filipa on whether it's the last or other indeed. At any case though, the `last` would be `--last` to yet keep the BEM naming conventions.

**Comment by emeryro** [comment]
As it appears that the modification required is in the footer, and not in social media links component, this pull request can be closed without merge

**Pull request closed without merging**
