### PR TITLE
docs(gallery): add version01

### PR DESCRIPTION
**Pull request by kibos11**
This is the first commit of this content (just a wiki mirror)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 71beccc9f1a75591ebb4f4bf6e61f05c5bea4707

https://deploy-preview-848--europa-component-library.netlify.com

**Review by yhuard — APPROVED** [review]

**Review by yhuard — DISMISSED** [review]

**Review by degliwe — CHANGES_REQUESTED** [review]
- the screenshot contain arrow pointing  in the wrong direction
- the thumbnails on the right panel of the modal should be removed (we agreed to remove them from the specs)

**Comment by kibos11** [comment]
Arrows will replaced soon

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thanasisrig** [comment]
@degliwe But the overlay for the gallery has thumbnails correct? Only in some cases, we remove them based on the responsive behaviour.

**Comment by degliwe** [comment]
@thanasisrig reading this comment, I understand that we agreed to drop it (in order to do like the current version) https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Gallery+Design+Specifications?preview=/827234519/829490473/1/830277606/overlay-web.png

**Pull request closed without merging**
