### PR TITLE
feat(listings): date listings - INNO-803

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Date listing component

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [x] `package.json` is up-to-date and `@ec-europa/ecl-base` is part of the dependencies
- [x] I have checked the dependencies
- [x] I have given the fractal status “ready” to my component
- [x] I have declared `@define mycomponent` in the SCSS file
- [x] I have specified `margin: 0;` on the CSS component
- [x] I have provided tests
- [x] I follow the naming guidelines
- [x] the component supports composition
- [x] there are no hardcoded strings (all content come from the context)
- [x] I have filled the README.md file (at least a few lines)
- [x] My component is listed in the root README
- [x] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit cc92b7ffa499ad2c8b3a07e47c8a92c2ce0b9d00

https://deploy-preview-437--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit 7ecb2900afcfc10015bfad8a3539ebc9764b0ebd

https://deploy-preview-437--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview ready!

Built with commit 1d8d5e6c41a4410fe405a1be8e2f0b45fb24b324

https://deploy-preview-437--europa-component-library.netlify.com

**Review by degliwe — CHANGES_REQUESTED** [review]
Overall looks good.
Few remarks:
- the 2 col layout is missing.
- I'm with 1 page for all the list items variants.
- The more I think about, the more I think it makes more sense to put "listings" in the template section.

**Comment by emeryro** [comment]
There is already a "listings" template (with two columns display)

**Review by degliwe — APPROVED** [review]

**Comment by degliwe** [comment]
build failed because of lorempixel response time so I approve

**Pull request merged**
