### PR TITLE
refactor(menu): menu improvements - INNO-2005

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

- [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
- [ ] I have checked the dependencies
- [ ] I have given the fractal status “ready” to my component
- [ ] I have declared `@define mycomponent` in the SCSS file
- [ ] I have specified `margin: 0;` on the CSS component
- [ ] I have provided tests
- [ ] I follow the naming guidelines
- [ ] the component supports composition
- [ ] there are no hardcoded strings (all content come from the context)
- [ ] I have filled the README.md file (at least a few lines)
- [ ] My component is listed in the root README
- [ ] My PR has the right label(s)
- [ ] The redirects in `src/website/src/routes/Redirects.jsx` are up-to-date

### CODE REVIEW

**Comment by planctus** [comment]
To me the implementation is fine, basing on the feedback by the designer we should:

- have 16px "padding" around the columns
- fix the width of each column in the dropdown to 248px
- see which are the possibilities in aligning items in cells of the same row with a different text length (like middle alignment), (filipa is concerned by the strange look of the columns in the 4th item dropdown)

**Review by planctus — CHANGES_REQUESTED** [review]
Just based on the first feedback by Filipa, a few changes.
She could send a new mock with more specs, if needed, we can request it, otherwise if the info in the review comment are enough, we can procede.

**Comment by planctus** [comment]
@emeryro , the designer says there is a missing blue line "at the end of the menu", hope you can identify which one it is.. :)
Then the solution of the center alignment in the cells of the grid has been "approved" by the designer, or at least she gave us the green light to set a demo with that, she will then review it again.
So, with these two things we should (??) be able to close this iteration ;)

**Comment by emeryro** [comment]
ok, I will update the PR

**Comment by planctus** [comment]
Fine for me, let's wait for the designer's approval ;)

**Review by planctus — APPROVED** [review]

**Pull request merged**
