### PR TITLE
fix(dependencies): update all package.json - INNO-1038

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit c269a7f12f66fb9c50657b79126177c85e9e446e

https://deploy-preview-674--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 73a4d395a754fa78042181606b3322d5a9bd3415

https://deploy-preview-674--europa-component-library.netlify.com

**Comment by kalinchernev** [comment]
One component with questions: `@ecl/generic-component-dialog`, in twig, there are usages of the screen reader utility, headings and the dismiss button `@ecl/generic-component-message`

**Review by raduchiriac — COMMENTED** [review]
timeline:
- remove `"@ecl/generic-style-typography-paragraph": "^0.0.1"`

site-header:
- remove `"@ecl/generic-style-icon": "^0.0.1"`

side-navigation:
- remove `"@ecl/generic-style-icon": "^0.0.1"`

**Comment by kalinchernev** [comment]
Question on `@ecl/generic-component-dropdown`:
These deps are not used neither in the scss, nor in the twig templates
```
    "@ecl/generic-component-expandable": "^0.0.1",
    "@ecl/generic-style-icon": "^0.0.1",
```
However, they are to be used looking at [the preview](https://next--europa-component-library.netlify.com/ec/components/detail/ec-component-dropdown), they seem to be needed. Do we check also for deps of deps?
Also, any idea why the dropdown doesn't work any more?

**Comment by kalinchernev** [comment]
Question in `@ecl/generic-component-expandable`, I'm not sure these are actual dependencies:
```
    "@ecl/generic-component-button": "^0.0.1",
    "@ecl/generic-component-link": "^0.0.1",
```
Templates use them, but they are not really required, right?

**Comment by kalinchernev** [comment]
Question in `@ecl/generic-component-footer`: because of [`ecl-u-d-inline`](https://github.com/ec-europa/europa-component-library/blob/next/src/generic/generic-component-footer/generic-component-footer.twig#L48), maybe the `@ecl/generic-utility-display` is also needed.

**Review by kalinchernev — COMMENTED** [review]
`@ecl/generic-component-dialog`:

In twig, there are usages of the screen reader utility, headings and the dismiss button `@ecl/generic-component-message`

----

`@ecl/generic-component-dropdown`:

These deps are not used neither in the scss, nor in the twig templates
```
    "@ecl/generic-component-expandable": "^0.0.1",
    "@ecl/generic-style-icon": "^0.0.1",
```
However, they are to be used looking at [the preview](https://next--europa-component-library.netlify.com/ec/components/detail/ec-component-dropdown), they seem to be needed. Do we check also for deps of deps?
Also, any idea why the dropdown doesn't work any more?

----------

`@ecl/generic-component-expandable`:

```
    "@ecl/generic-component-button": "^0.0.1",
    "@ecl/generic-component-link": "^0.0.1",
```
Templates use them, but they are not really required, right?

--------

`@ecl/generic-component-footer`: 

because of [`ecl-u-d-inline`](https://github.com/ec-europa/europa-component-library/blob/next/src/generic/generic-component-footer/generic-component-footer.twig#L48), maybe the `@ecl/generic-utility-display` is also needed.

------

`@ecl/generic-component-language-list`:

- `ecl-u-mh-auto` -> please add `@ecl/generic-utility-margin`
- `ecl-u-f` -> please add `@ecl/generic-utility-float`

**Review by kalinchernev — APPROVED** [review]

**Pull request merged**
