### PR TITLE
feat(fractal): move fractal theme into the main repo - INNO-736

### PR DESCRIPTION
**Pull request by yhuard**
Fractal theme moved into this repo. Uses ecl-preset-full-ec.

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 4276ef531e22876ffb94a890adde16eab4fe153d

https://deploy-preview-598--europa-component-library.netlify.com

**Review by kalinchernev — COMMENTED** [review]
Seems to work fine. Favicons in `packages/ecl-fractal-theme/assets/img/favicon` don't really need to be in version as they are already available in `src/flavors/ec/images/favicon`

**Comment by yhuard** [comment]
thanks @kalinchernev, I'll check the icons thing :)

**Comment by yhuard** [comment]
in fact, keeping the favicons `src/flavors/ec/images/favicon` doesn't make sense

we could have a new directory called `ressources` where they belong, but surely not in `src/flavors/ec/images/favicon` :P

**Review by kalinchernev — APPROVED** [review]
Works well, thanks

**Pull request merged**
