### PR TITLE
refactor(scss): normalize SCSS files S01E11 - INNO-1020

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

table, timeline, grid, icon, image, typography

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 6b3596bba09c9ae3e6432db6747e3ed84ded73b9

https://deploy-preview-668--europa-component-library.netlify.com

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 8995da7694412e025dd0a4056b150e773dd8ceda

https://deploy-preview-668--europa-component-library.netlify.com

**Review by kalinchernev — CHANGES_REQUESTED** [review]
Could you please add `@include check-imports(('*-component-button'));` in tag component? Its template has `ecl-tag__item` rule which adds on the button.

**Review by kalinchernev — APPROVED** [review]
Thanks!

**Pull request merged**
