### PR TITLE
fix: use outline for form elements - INNO-1318

### PR DESCRIPTION
**Pull request by planctus**
# PR description

Please drop a few lines about the PR: what it does, how to test it, etc.

## QA Checklist

In order to ensure a safe and quick review, please check that your PR follow those guidelines:

* [ ] `package.json` is up-to-date and `@ecl/[system]-base` is part of the dependencies
* [ ] I have checked the dependencies
* [ ] I have given the fractal status “ready” to my component
* [ ] I have declared `@define mycomponent` in the SCSS file
* [ ] I have specified `margin: 0;` on the CSS component
* [ ] I have provided tests
* [ ] I follow the naming guidelines
* [ ] the component supports composition
* [ ] there are no hardcoded strings (all content come from the context)
* [ ] I have filled the README.md file (at least a few lines)
* [ ] My component is listed in the root README
* [ ] My PR has the right label(s)

### CODE REVIEW

**Comment by HAL-Patch-INNO** [comment]
Deploy preview for *europa-component-library* ready!

Built with commit 2e97985d9e875d0b9d0f49aa1e4cd2d98857fd13

https://deploy-preview-1000--europa-component-library.netlify.com

**Review by emeryro — CHANGES_REQUESTED** [review]
Using a macro here seems to be a good idea.
But the result isn't as expected; the values passed to the browser are strings so it isn't taken into account.
image

**Comment by yhuard** [comment]
> Using a macro here seems to be a good idea.
> But the result isn't as expected; the values passed to the browser are strings so it isn't taken into account.
> image

we should have deleted this mixin long ago... it's not used anywhere and it makes the code less readable :(

**Comment by planctus** [comment]
Well, i saw we had a mixin and i used that, it's true that the advantage of using it is questionable but since it is a repeated chunk of code the one we would use, a mixin is still the way i would go for.
Anyway, since this was already "deprecated",  i'll remove the usage of the mixin and the mixin file at this point ;)
Thanks for the reviews

**Review by emeryro — APPROVED** [review]

**Review by yhuard — APPROVED** [review]

**Pull request merged**
