### PR TITLE
feat(label): add component - FRONT-1006

### PR DESCRIPTION
**Pull request by emeryro**
# PR description

specs: 

- https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/Label+Component
- https://webgate.ec.europa.eu/CITnet/confluence/display/NEXTEUROPA/2020-03+Label+-+ECL+Page+-+final

### CODE REVIEW

**Review by papegaill — CHANGES_REQUESTED** [review]
Everything ok to me 👍

The only remark would be the documentation images that seems more blurry than the ones provided by the designers?

Screenshot 2020-04-16 at 13 26 05

vs 

Screenshot 2020-04-16 at 13 28 25

**Comment by emeryro** [comment]
I removed the shadow under images. It should be better

**Comment by papegaill** [comment]
@emeryro Thank you but it's still the same, but I see the problem, you resized down images and as I have retina display these images seems more blurry.. I don't know images rules on documentation part? retina or not?

**Comment by emeryro** [comment]
There are no rules for images.
Indeed, I had to resize them. If that really is an issue, I can display them at full size, but then It won't be accurate.
To me it is fine as it is now

**Review by papegaill — APPROVED** [review]
sure, this is the case for all the images for the doc, so this is another topic.

**Comment by emeryro** [comment]
component has been validated by designers:
image

**Pull request merged**
